import type { Metadata } from "next";
import "./globals.css";

import localfont from "next/font/local";


const involve = localfont (
  {
    src: [
      {
        path: "../../public/fonts/TTF/Involve-Regular.ttf",
        weight: "400"
      }
    ],
    variable: "--font-involve"
  }
)

const involveBold = localfont (
  {
    src: [
      {
        path: "../../public/fonts/TTF/Involve-Bold.ttf",
        weight: "700"
      }
    ],
    variable: "--font-involve-bold"
  }
)



export const metadata: Metadata = {
  title: "Test Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${involve.variable} ${involveBold.variable}`}>
        {children}
      </body>
    </html>
  );
}
